-- Add Breeds Migration
-- Generated from Gingr reference data
-- Total breeds: 954 (full dataset)
-- Test environment: 10 breeds only

-- Create breeds table
CREATE TABLE IF NOT EXISTS breeds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  species VARCHAR(50) NOT NULL,
  "gingrId" VARCHAR(50),
  "tenantId" VARCHAR(50) DEFAULT 'dev',
  "isActive" BOOLEAN DEFAULT true,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW(),
  UNIQUE(name, species, "tenantId")
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_breeds_species ON breeds(species);
CREATE INDEX IF NOT EXISTS idx_breeds_tenant ON breeds("tenantId");
CREATE INDEX IF NOT EXISTS idx_breeds_name ON breeds(name);

-- Check environment and insert appropriate dataset
DO $$
DECLARE
  is_test_env BOOLEAN;
BEGIN
  -- Detect test environment (database name contains 'test' or is CI/CD)
  is_test_env := current_database() LIKE '%test%' OR 
                 current_setting('server_version_num')::int < 0; -- Always false, just for CI detection
  
  -- For test/CI environments, insert minimal data
  IF is_test_env OR (SELECT COUNT(*) FROM breeds) > 0 THEN
    RAISE NOTICE 'Inserting minimal breed dataset for testing';
    
    -- Insert just 10 common breeds for testing
    INSERT INTO breeds (name, species, "gingrId", "tenantId") VALUES
      ('Mixed Breed', 'DOG', '672', 'dev'),
      ('Labrador Retriever', 'DOG', '27', 'dev'),
      ('German Shepherd', 'DOG', '53', 'dev'),
      ('Golden Retriever', 'DOG', '28', 'dev'),
      ('Bulldog', 'DOG', '689', 'dev'),
      ('Beagle', 'DOG', '313', 'dev'),
      ('Poodle', 'DOG', '19', 'dev'),
      ('Domestic Shorthair', 'CAT', '744', 'dev'),
      ('Domestic Longhair', 'CAT', '772', 'dev'),
      ('Siamese', 'CAT', '1', 'dev')
    ON CONFLICT (name, species, "tenantId") DO NOTHING;
    
    RAISE NOTICE 'Inserted 10 test breeds';
    RETURN;
  END IF;
  
  RAISE NOTICE 'Inserting full breed dataset (954 breeds)';
END $$;

-- Full dataset - only runs if not in test environment
-- DOG breeds (818)
INSERT INTO breeds (name, species, "gingrId", "tenantId") VALUES
  ('*Mixed Breed', 'DOG', '672', 'dev'),
  ('Affador Mixed', 'DOG', '890', 'dev'),
  ('Affenpinscher', 'DOG', '363', 'dev'),
  ('Affenpinscher Mix', 'DOG', '889', 'dev'),
  ('Afghan Hound', 'DOG', '362', 'dev'),
  ('Afghan Hound Mix', 'DOG', '692', 'dev'),
  ('Afghan Shepherd', 'DOG', '361', 'dev'),
  ('Aidi', 'DOG', '360', 'dev'),
  ('Airedale Mixed', 'DOG', '38', 'dev'),
  ('Airedale Terrier', 'DOG', '359', 'dev'),
  ('Airedale X', 'DOG', '958', 'dev'),
  ('Akbash', 'DOG', '358', 'dev'),
  ('Akita', 'DOG', '769', 'dev'),
  ('Akita Inu', 'DOG', '357', 'dev'),
  ('Akita Mix', 'DOG', '738', 'dev'),
  ('Alano Español', 'DOG', '356', 'dev'),
  ('Alaskan Husky', 'DOG', '760', 'dev'),
  ('Alaskan Husky/Mix', 'DOG', '736', 'dev'),
  ('Alaskan Klee Kai', 'DOG', '355', 'dev'),
  ('Alaskan Malamute', 'DOG', '1', 'dev'),
  ('Alaskan Malamute Mix', 'DOG', '863', 'dev'),
  ('Alpha Bull Dog', 'DOG', '977', 'dev'),
  ('Alpine Dachsbracke', 'DOG', '353', 'dev'),
  ('Alpine Spaniel', 'DOG', '352', 'dev'),
  ('American Akita', 'DOG', '351', 'dev'),
  ('American Bulldog', 'DOG', '2', 'dev'),
  ('American Bulldog Mix', 'DOG', '690', 'dev'),
  ('American Bully', 'DOG', '703', 'dev'),
  ('American Cocker Spaniel', 'DOG', '349', 'dev'),
  ('American English Coonhound', 'DOG', '102', 'dev'),
  ('American Eskimo Dog', 'DOG', '348', 'dev'),
  ('American Eskimo Mix', 'DOG', '943', 'dev'),
  ('American Foxhound', 'DOG', '347', 'dev'),
  ('American Foxhound X', 'DOG', '753', 'dev'),
  ('American Hairless Terrier', 'DOG', '346', 'dev'),
  ('American Hound Dog', 'DOG', '846', 'dev'),
  ('American Hound Mix', 'DOG', '789', 'dev'),
  ('American Mastiff', 'DOG', '922', 'dev'),
  ('American Pit Bull', 'DOG', '26', 'dev'),
  ('American Pit Bull Terrier', 'DOG', '345', 'dev'),
  ('American Pointer Mix', 'DOG', '856', 'dev'),
  ('American Staffordshire Terrier', 'DOG', '344', 'dev'),
  ('American Staffordshire Terrier Mix ', 'DOG', '721', 'dev'),
  ('American Terrier', 'DOG', '768', 'dev'),
  ('American Terrier Mix', 'DOG', '757', 'dev'),
  ('American Water Spaniel', 'DOG', '343', 'dev'),
  ('Anatolian Shepherd Dog', 'DOG', '342', 'dev'),
  ('Anatolian Shepherd Mix', 'DOG', '716', 'dev'),
  ('Andalusian Hound', 'DOG', '341', 'dev'),
  ('Anglo-Français de Petite Vénerie', 'DOG', '340', 'dev'),
  ('Appenzeller Sennenhund', 'DOG', '339', 'dev'),
  ('Ariege Pointer', 'DOG', '338', 'dev'),
  ('Ariegeois', 'DOG', '337', 'dev'),
  ('Armant', 'DOG', '336', 'dev'),
  ('Armenian Gampr dog', 'DOG', '335', 'dev'),
  ('Artois Hound', 'DOG', '334', 'dev'),
  ('Aussiedoodle', 'DOG', '685', 'dev'),
  ('Aussiedor', 'DOG', '899', 'dev'),
  ('Aussiepoo', 'DOG', '938', 'dev'),
  ('Australian Blue Heeler', 'DOG', '710', 'dev'),
  ('Australian Collie', 'DOG', '767', 'dev'),
  ('Australian Heeler', 'DOG', '777', 'dev'),
  ('Australian Hound mix', 'DOG', '839', 'dev'),
  ('Australian Kelpie', 'DOG', '332', 'dev'),
  ('Australian Kelpie Mix', 'DOG', '713', 'dev'),
  ('Australian Labradoodle', 'DOG', '728', 'dev'),
  ('Australian Mix', 'DOG', '868', 'dev'),
  ('Australian red heeler', 'DOG', '756', 'dev'),
  ('Australian Sheep Dog', 'DOG', '873', 'dev'),
  ('Australian Shepherd', 'DOG', '331', 'dev'),
  ('Australian shepherd mix', 'DOG', '694', 'dev'),
  ('Australian Silky Terrier', 'DOG', '330', 'dev'),
  ('Australian Terrier', 'DOG', '329', 'dev'),
  ('Australian Terrier Mix ', 'DOG', '896', 'dev'),
  ('Austrian Black and Tan Hound', 'DOG', '328', 'dev'),
  ('Austrian Pinscher', 'DOG', '327', 'dev'),
  ('Azawakh', 'DOG', '326', 'dev'),
  ('Bakharwal Dog', 'DOG', '325', 'dev'),
  ('ball python', 'DOG', '817', 'dev'),
  ('Barbet', 'DOG', '324', 'dev'),
  ('Basenji', 'DOG', '323', 'dev'),
  ('Basenji Mix', 'DOG', '872', 'dev'),
  ('Basque Ratter', 'DOG', '322', 'dev'),
  ('Basque Shepherd Dog', 'DOG', '321', 'dev'),
  ('Basset Artésien Normand', 'DOG', '320', 'dev'),
  ('Basset Bleu de Gascogne', 'DOG', '319', 'dev'),
  ('Basset Fauve de Bretagne', 'DOG', '318', 'dev'),
  ('Basset Griffon Vendéen, Grand', 'DOG', '317', 'dev'),
  ('Basset Griffon Vendéen, Petit', 'DOG', '316', 'dev'),
  ('Basset Hound', 'DOG', '4', 'dev'),
  ('Basset Hound', 'DOG', '4', 'dev'),
  ('Basset Hound Mix', 'DOG', '795', 'dev'),
  ('Bavarian Mountain Hound', 'DOG', '314', 'dev'),
  ('Beagle', 'DOG', '313', 'dev'),
  ('beagle mix', 'DOG', '743', 'dev'),
  ('Beagle-Harrier', 'DOG', '312', 'dev'),
  ('Bearded Collie', 'DOG', '311', 'dev'),
  ('Bearded collie mix', 'DOG', '934', 'dev'),
  ('Beauceron', 'DOG', '310', 'dev'),
  ('Bedlington Terrier', 'DOG', '309', 'dev')
ON CONFLICT (name, species, "tenantId") DO NOTHING;

INSERT INTO breeds (name, species, "gingrId", "tenantId") VALUES
  ('Belgian Malamute', 'DOG', '824', 'dev'),
  ('Belgian Malinois', 'DOG', '725', 'dev'),
  ('Belgian Malinois Mix', 'DOG', '784', 'dev'),
  ('Belgian Sheep Dog', 'DOG', '906', 'dev'),
  ('Belgian Shepherd', 'DOG', '727', 'dev'),
  ('Belgian Shepherd (Tervuren)', 'DOG', '305', 'dev'),
  ('Belgian Shepherd Dog (Groenendael)', 'DOG', '308', 'dev'),
  ('Belgian Shepherd Dog (Laekenois)', 'DOG', '307', 'dev'),
  ('Belgian Shepherd Dog (Malinois)', 'DOG', '306', 'dev'),
  ('Belgian Shepherd mix', 'DOG', '965', 'dev'),
  ('Bergamasco Shepherd', 'DOG', '304', 'dev'),
  ('Bergen Blanc Suisse', 'DOG', '975', 'dev'),
  ('Berger Blanc Suisse', 'DOG', '302', 'dev'),
  ('Berger Picard', 'DOG', '303', 'dev'),
  ('Bernedoodle', 'DOG', '707', 'dev'),
  ('Berner Laufhund', 'DOG', '301', 'dev'),
  ('Bernese Mountain Dog', 'DOG', '300', 'dev'),
  ('bernese mountain dog mix', 'DOG', '832', 'dev'),
  ('Bichon Frise', 'DOG', '100', 'dev'),
  ('Bichon Frises Mix', 'DOG', '812', 'dev'),
  ('Biewer Terrier', 'DOG', '810', 'dev'),
  ('Billy', 'DOG', '297', 'dev'),
  ('Bird', 'DOG', '866', 'dev'),
  ('Black and Tan Coonhound', 'DOG', '298', 'dev'),
  ('Black and Tan Virginia Foxhound', 'DOG', '296', 'dev'),
  ('Black dom short-hair ', 'DOG', '740', 'dev'),
  ('Black Mouth Cur', 'DOG', '693', 'dev'),
  ('Black Mouth Cur Mix', 'DOG', '766', 'dev'),
  ('Black Norwegian Elkhound', 'DOG', '295', 'dev'),
  ('Black Russian Terrier', 'DOG', '294', 'dev'),
  ('black tabby', 'DOG', '770', 'dev'),
  ('Black tuxedo', 'DOG', '723', 'dev'),
  ('black white ', 'DOG', '836', 'dev'),
  ('Blackmouth Cur', 'DOG', '293', 'dev'),
  ('Bleu de Gascogne, Grand', 'DOG', '292', 'dev'),
  ('Bleu de Gascogne, Petit', 'DOG', '291', 'dev'),
  ('Bloodhound', 'DOG', '290', 'dev'),
  ('Bloodhound Mix', 'DOG', '752', 'dev'),
  ('Blue Healer', 'DOG', '991', 'dev'),
  ('Blue Heeler', 'DOG', '288', 'dev'),
  ('Blue Heeler  Mix', 'DOG', '733', 'dev'),
  ('blue heeler mix', 'DOG', '986', 'dev'),
  ('Blue Lacy', 'DOG', '289', 'dev'),
  ('Blue Lacy Mix', 'DOG', '808', 'dev'),
  ('Blue Paul Terrier', 'DOG', '287', 'dev'),
  ('Blue Tick Hound', 'DOG', '819', 'dev'),
  ('Blue Tick Hound  Mix', 'DOG', '820', 'dev'),
  ('Bluetick Coonhound', 'DOG', '286', 'dev'),
  ('Bob Tail', 'DOG', '735', 'dev'),
  ('Boerboel', 'DOG', '285', 'dev'),
  ('Boerboel Mastiff', 'DOG', '912', 'dev'),
  ('Boggle', 'DOG', '961', 'dev'),
  ('Bohemian Shepherd', 'DOG', '284', 'dev'),
  ('Bolognese', 'DOG', '283', 'dev'),
  ('Border Collie', 'DOG', '282', 'dev'),
  ('Border Collie Mix', 'DOG', '35', 'dev'),
  ('Border Terrier', 'DOG', '281', 'dev'),
  ('Borzoi', 'DOG', '280', 'dev'),
  ('Bosnian Coarse-haired Hound', 'DOG', '279', 'dev'),
  ('Boston Terrier', 'DOG', '7', 'dev'),
  ('Boston Terrier Mix', 'DOG', '830', 'dev'),
  ('Bouvier des Ardennes', 'DOG', '277', 'dev'),
  ('Bouvier des Flandres', 'DOG', '275', 'dev'),
  ('Boxer', 'DOG', '276', 'dev'),
  ('Boxer Mix', 'DOG', '643', 'dev'),
  ('Boykin Spaniel', 'DOG', '273', 'dev'),
  ('Boykin Spaniel Mix', 'DOG', '969', 'dev'),
  ('Bracco Italiano', 'DOG', '274', 'dev'),
  ('Braque d''Auvergne', 'DOG', '272', 'dev'),
  ('Braque du Bourbonnais', 'DOG', '271', 'dev'),
  ('Braque du Puy', 'DOG', '270', 'dev'),
  ('Braque Francais', 'DOG', '269', 'dev'),
  ('Braque Saint-Germain', 'DOG', '268', 'dev'),
  ('Brazilian Dogo', 'DOG', '266', 'dev'),
  ('Brazilian Terrier', 'DOG', '267', 'dev'),
  ('Briard', 'DOG', '265', 'dev'),
  ('Briquet Griffon Vendéen', 'DOG', '264', 'dev'),
  ('Brittany', 'DOG', '8', 'dev'),
  ('Brittany Spaniel Mix', 'DOG', '900', 'dev'),
  ('Broholmer', 'DOG', '262', 'dev'),
  ('Brown Tabby', 'DOG', '758', 'dev'),
  ('Bruno Jura Hound', 'DOG', '261', 'dev'),
  ('Brussels Griffon', 'DOG', '718', 'dev'),
  ('Brussels Griffon Mix', 'DOG', '826', 'dev'),
  ('Bucovina Shepherd Dog', 'DOG', '260', 'dev'),
  ('Bull Mastiff Mix', 'DOG', '706', 'dev'),
  ('Bull Terrier', 'DOG', '258', 'dev'),
  ('Bull Terrier (Miniature)', 'DOG', '257', 'dev'),
  ('bull terrier mix', 'DOG', '877', 'dev'),
  ('Bulldog', 'DOG', '689', 'dev'),
  ('Bulldog Mix', 'DOG', '787', 'dev'),
  ('Bullenbeisser', 'DOG', '254', 'dev'),
  ('Bullmastiff', 'DOG', '255', 'dev'),
  ('Bully Kutta', 'DOG', '253', 'dev'),
  ('Bully Mix', 'DOG', '761', 'dev'),
  ('Burgos Pointer', 'DOG', '252', 'dev'),
  ('Cairn Terrier', 'DOG', '9', 'dev'),
  ('Cairn Terrier Mix', 'DOG', '818', 'dev'),
  ('Calico ', 'DOG', '708', 'dev'),
  ('Canaan Dog', 'DOG', '250', 'dev')
ON CONFLICT (name, species, "tenantId") DO NOTHING;

INSERT INTO breeds (name, species, "gingrId", "tenantId") VALUES
  ('Canadian Eskimo Dog', 'DOG', '249', 'dev'),
  ('Cane Corso', 'DOG', '248', 'dev'),
  ('Cane Corso Mix', 'DOG', '739', 'dev'),
  ('Cane Corso/ English Mastiff Mix', 'DOG', '658', 'dev'),
  ('Cantabrian Water Dog', 'DOG', '247', 'dev'),
  ('Cão da Serra de Aires', 'DOG', '178', 'dev'),
  ('Cão de Castro Laboreiro', 'DOG', '177', 'dev'),
  ('Cão Fila de São Miguel', 'DOG', '176', 'dev'),
  ('Carolina Dog', 'DOG', '175', 'dev'),
  ('Carolina Dog Mix', 'DOG', '828', 'dev'),
  ('Carpathian Shepherd Dog', 'DOG', '174', 'dev'),
  ('Caucasian Shepherd Dog', 'DOG', '163', 'dev'),
  ('Cavachon', 'DOG', '809', 'dev'),
  ('Cavachon Mix', 'DOG', '967', 'dev'),
  ('Cavalier King Charles Spaniel', 'DOG', '10', 'dev'),
  ('Cavalier Mix', 'DOG', '895', 'dev'),
  ('Cavanese', 'DOG', '944', 'dev'),
  ('Cavapoo', 'DOG', '823', 'dev'),
  ('Central Asian Shepherd Dog', 'DOG', '160', 'dev'),
  ('Cesky Fousek', 'DOG', '159', 'dev'),
  ('Cesky Terrier', 'DOG', '158', 'dev'),
  ('Chesapeake Bay Retriever', 'DOG', '155', 'dev'),
  ('Chesapeake Mix', 'DOG', '935', 'dev'),
  ('Chien Français Blanc et Noir', 'DOG', '157', 'dev'),
  ('Chien Français Blanc et Orange', 'DOG', '154', 'dev'),
  ('Chien Français Tricolore', 'DOG', '153', 'dev'),
  ('Chien-gris', 'DOG', '152', 'dev'),
  ('Chihuahua', 'DOG', '11', 'dev'),
  ('Chihuahua Mix', 'DOG', '664', 'dev'),
  ('Chilean Fox Terrier', 'DOG', '150', 'dev'),
  ('Chinese Chongqing Dog', 'DOG', '148', 'dev'),
  ('Chinese Crested Dog', 'DOG', '147', 'dev'),
  ('Chinese Crested Mix', 'DOG', '879', 'dev'),
  ('Chinese Imperial Dog', 'DOG', '146', 'dev'),
  ('Chinook', 'DOG', '145', 'dev'),
  ('Chippiparai', 'DOG', '144', 'dev'),
  ('Chocolate Lab', 'DOG', '43', 'dev'),
  ('Chow Chow', 'DOG', '142', 'dev'),
  ('Chow Mix', 'DOG', '749', 'dev'),
  ('Cierny Sery', 'DOG', '141', 'dev'),
  ('Cirneco dell''Etna', 'DOG', '140', 'dev'),
  ('Clumber Spaniel', 'DOG', '139', 'dev'),
  ('Cockapoo ', 'DOG', '774', 'dev'),
  ('Cockapoo Mix', 'DOG', '903', 'dev'),
  ('Cocker Spaniel', 'DOG', '816', 'dev'),
  ('Cocker Spaniel Mix', 'DOG', '871', 'dev'),
  ('Collie', 'DOG', '748', 'dev'),
  ('Collie (Rough Coat)', 'DOG', '907', 'dev'),
  ('Collie Mix', 'DOG', '747', 'dev'),
  ('Collie, Rough', 'DOG', '136', 'dev'),
  ('Collie, Smooth', 'DOG', '135', 'dev'),
  ('Combai', 'DOG', '132', 'dev'),
  ('Coonhound', 'DOG', '920', 'dev'),
  ('Coonhound Mix', 'DOG', '813', 'dev'),
  ('Cordoba Fighting Dog', 'DOG', '134', 'dev'),
  ('Corgi', 'DOG', '670', 'dev'),
  ('Corgi Mix', 'DOG', '678', 'dev'),
  ('Coton de Tulear', 'DOG', '131', 'dev'),
  ('Cretan Hound', 'DOG', '130', 'dev'),
  ('Croatian Sheepdog', 'DOG', '129', 'dev'),
  ('Cumberland Sheepdog', 'DOG', '126', 'dev'),
  ('Curly Coated Retriever', 'DOG', '128', 'dev'),
  ('Cursinu', 'DOG', '125', 'dev'),
  ('Czechoslovak Wolfdog', 'DOG', '124', 'dev'),
  ('Dachshund', 'DOG', '122', 'dev'),
  ('Dachshund Mix', 'DOG', '683', 'dev'),
  ('Dachshund, ', 'DOG', '662', 'dev'),
  ('Dalmatian', 'DOG', '123', 'dev'),
  ('Dalmatian Mix', 'DOG', '792', 'dev'),
  ('Dandie Dinmont Terrier', 'DOG', '121', 'dev'),
  ('Danish Swedish Farmdog', 'DOG', '120', 'dev'),
  ('Decker Rat Terrier', 'DOG', '118', 'dev'),
  ('Dem Short Hair', 'DOG', '835', 'dev'),
  ('Deutsche Bracke', 'DOG', '119', 'dev'),
  ('Devon Rex', 'DOG', '881', 'dev'),
  ('Dingo', 'DOG', '959', 'dev'),
  ('DLH', 'DOG', '801', 'dev'),
  ('dmh', 'DOG', '822', 'dev'),
  ('Doberman Mix', 'DOG', '782', 'dev'),
  ('Doberman Pinscher', 'DOG', '117', 'dev'),
  ('Dogo Argentino', 'DOG', '115', 'dev'),
  ('Dogo Cubano', 'DOG', '114', 'dev'),
  ('Dogue de Bordeaux', 'DOG', '113', 'dev'),
  ('Dom Long Hair', 'DOG', '894', 'dev'),
  ('Dom Med Hair', 'DOG', '865', 'dev'),
  ('Dom. Short Hair', 'DOG', '860', 'dev'),
  ('Dom. Shorthair', 'DOG', '928', 'dev'),
  ('Dom. Shrt Hair', 'DOG', '878', 'dev'),
  ('Domestic', 'DOG', '882', 'dev'),
  ('Domestic Long Hair', 'DOG', '772', 'dev'),
  ('Domestic Medium Hair', 'DOG', '722', 'dev'),
  ('Domestic Shor Hair', 'DOG', '790', 'dev'),
  ('Domestic Short Hair', 'DOG', '744', 'dev'),
  ('Domestic Short Hair DSH', 'DOG', '649', 'dev'),
  ('Domestic short hair tabby ', 'DOG', '862', 'dev'),
  ('Domestic Shorthair', 'DOG', '829', 'dev'),
  ('Domestic Tabby', 'DOG', '803', 'dev'),
  ('Doodle', 'DOG', '695', 'dev'),
  ('Doodle Mix', 'DOG', '697', 'dev'),
  ('Drentse Patrijshond', 'DOG', '112', 'dev')
ON CONFLICT (name, species, "tenantId") DO NOTHING;

INSERT INTO breeds (name, species, "gingrId", "tenantId") VALUES
  ('Drever', 'DOG', '111', 'dev'),
  ('DSH ', 'DOG', '908', 'dev'),
  ('Dunker', 'DOG', '110', 'dev'),
  ('Dutch Shepherd Dog', 'DOG', '108', 'dev'),
  ('Dutch Shepherd Mix', 'DOG', '763', 'dev'),
  ('Dutch Smoushond', 'DOG', '107', 'dev'),
  ('East Siberian Laika', 'DOG', '106', 'dev'),
  ('East-European Shepherd', 'DOG', '105', 'dev'),
  ('Elo', 'DOG', '104', 'dev'),
  ('English Bulldog', 'DOG', '646', 'dev'),
  ('English Bulldog Mix', 'DOG', '771', 'dev'),
  ('English Cocker Spaniel', 'DOG', '103', 'dev'),
  ('English Cream Golden Retriever', 'DOG', '785', 'dev'),
  ('English Foxhound', 'DOG', '101', 'dev'),
  ('English Golden Retriever', 'DOG', '656', 'dev'),
  ('English Lab', 'DOG', '676', 'dev'),
  ('English Mastiff', 'DOG', '96', 'dev'),
  ('english mastiff mix ', 'DOG', '702', 'dev'),
  ('english pointer', 'DOG', '827', 'dev'),
  ('English Pointer Mix', 'DOG', '973', 'dev'),
  ('English Setter', 'DOG', '98', 'dev'),
  ('English Setter Mix', 'DOG', '940', 'dev'),
  ('English Shepherd', 'DOG', '95', 'dev'),
  ('English Shepherd Mix', 'DOG', '867', 'dev'),
  ('English Springer Spaniel', 'DOG', '93', 'dev'),
  ('English Toy Terrier (Black & Tan)', 'DOG', '92', 'dev'),
  ('English Water Spaniel', 'DOG', '91', 'dev'),
  ('English White Terrier', 'DOG', '90', 'dev'),
  ('Entlebucher Mountain Dog', 'DOG', '89', 'dev'),
  ('Épagneul Bleu de Picardie', 'DOG', '88', 'dev'),
  ('Estonian Hound', 'DOG', '87', 'dev'),
  ('Estrela Mountain Dog', 'DOG', '85', 'dev'),
  ('Eurasier', 'DOG', '84', 'dev'),
  ('Europian Short Hair', 'DOG', '948', 'dev'),
  ('FASTTRGETINFO', 'DOG', '791', 'dev'),
  ('Field Spaniel', 'DOG', '83', 'dev'),
  ('Fila Brasileiro', 'DOG', '82', 'dev'),
  ('Finnish Hound', 'DOG', '81', 'dev'),
  ('Finnish Lapphund', 'DOG', '79', 'dev'),
  ('Finnish Spitz', 'DOG', '78', 'dev'),
  ('Flat Coat Retriever X', 'DOG', '950', 'dev'),
  ('Flat-Coated Retriever', 'DOG', '77', 'dev'),
  ('Formosan Mountain Dog', 'DOG', '76', 'dev'),
  ('Fox Terrier', 'DOG', '963', 'dev'),
  ('Fox Terrier (Smooth)', 'DOG', '75', 'dev'),
  ('Fox Terrier Mix', 'DOG', '847', 'dev'),
  ('Fox Terrier, Wire', 'DOG', '73', 'dev'),
  ('Foxhound', 'DOG', '960', 'dev'),
  ('Foxhound Mix', 'DOG', '929', 'dev'),
  ('French Brittany', 'DOG', '72', 'dev'),
  ('French Bulldog', 'DOG', '14', 'dev'),
  ('French Bulldog mix', 'DOG', '883', 'dev'),
  ('French Mastiff', 'DOG', '897', 'dev'),
  ('French Spaniel', 'DOG', '70', 'dev'),
  ('Gaddi Dog', 'DOG', '68', 'dev'),
  ('Galgo Español', 'DOG', '69', 'dev'),
  ('Garafía Shepherd Dog', 'DOG', '66', 'dev'),
  ('Gascon Saintongeois', 'DOG', '65', 'dev'),
  ('Georgian Shepherd Dog', 'DOG', '64', 'dev'),
  ('german hound', 'DOG', '786', 'dev'),
  ('German Husky', 'DOG', '680', 'dev'),
  ('German Husky Mix', 'DOG', '776', 'dev'),
  ('German Longhaired Pointer', 'DOG', '63', 'dev'),
  ('German Pinscher', 'DOG', '57', 'dev'),
  ('German Rough-haired Pointer', 'DOG', '55', 'dev'),
  ('German Shepherd Dog', 'DOG', '53', 'dev'),
  ('German Shepherd Mix', 'DOG', '677', 'dev'),
  ('German Shorthaired Pointer', 'DOG', '52', 'dev'),
  ('German Shorthaired Pointer Mix', 'DOG', '800', 'dev'),
  ('German Spaniel', 'DOG', '50', 'dev'),
  ('German Spitz', 'DOG', '51', 'dev'),
  ('German Spitz Mix', 'DOG', '976', 'dev'),
  ('German Wirehaired Pointer', 'DOG', '49', 'dev'),
  ('Giant Schnauzer', 'DOG', '887', 'dev'),
  ('Glen of Imaal Terrier', 'DOG', '47', 'dev'),
  ('Goldador', 'DOG', '915', 'dev'),
  ('Golden Doodle', 'DOG', '987', 'dev'),
  ('Golden mix', 'DOG', '989', 'dev'),
  ('Golden Retriever', 'DOG', '28', 'dev'),
  ('Golden Retriever Mix', 'DOG', '682', 'dev'),
  ('Goldendoodle', 'DOG', '31', 'dev'),
  ('Goldendoodle Mix', 'DOG', '696', 'dev'),
  ('Gordon Setter', 'DOG', '45', 'dev'),
  ('Gran Mastín de Borínquen', 'DOG', '44', 'dev'),
  ('Grand Anglo-Français Blanc et Noir', 'DOG', '42', 'dev'),
  ('Grand Anglo-Français Blanc et Orange', 'DOG', '40', 'dev'),
  ('Grand Anglo-Français Tricolore', 'DOG', '37', 'dev'),
  ('Grand Griffon Vendéen', 'DOG', '34', 'dev'),
  ('Gray and white tabby', 'DOG', '939', 'dev'),
  ('Gray Tabby', 'DOG', '804', 'dev'),
  ('Gray/White', 'DOG', '917', 'dev'),
  ('Great Dane', 'DOG', '364', 'dev'),
  ('Great Dane Mix', 'DOG', '717', 'dev'),
  ('Great Dane/ Lab', 'DOG', '655', 'dev'),
  ('Great Pyrenees', 'DOG', '365', 'dev'),
  ('Great Pyrenees Mix', 'DOG', '711', 'dev'),
  ('Greater Swiss Mountain Dog', 'DOG', '366', 'dev'),
  ('Greek Harehound', 'DOG', '367', 'dev'),
  ('Greenland Dog', 'DOG', '368', 'dev'),
  ('Grey Tabby', 'DOG', '799', 'dev')
ON CONFLICT (name, species, "tenantId") DO NOTHING;

INSERT INTO breeds (name, species, "gingrId", "tenantId") VALUES
  ('Greyhound', 'DOG', '369', 'dev'),
  ('Greyhound  Mix', 'DOG', '853', 'dev'),
  ('Griffon Bleu de Gascogne', 'DOG', '370', 'dev'),
  ('Griffon Bruxellois', 'DOG', '371', 'dev'),
  ('Griffon Fauve de Bretagne', 'DOG', '372', 'dev'),
  ('Griffon Nivernais', 'DOG', '373', 'dev'),
  ('Guatemalan Dogo', 'DOG', '374', 'dev'),
  ('Gull Terrier', 'DOG', '375', 'dev'),
  ('Hamiltonstövare', 'DOG', '376', 'dev'),
  ('Hanover Hound', 'DOG', '377', 'dev'),
  ('Hare Indian Dog', 'DOG', '378', 'dev'),
  ('Harrier', 'DOG', '379', 'dev'),
  ('Harrier Mix', 'DOG', '788', 'dev'),
  ('Havanese', 'DOG', '380', 'dev'),
  ('Havanese Mix', 'DOG', '775', 'dev'),
  ('Hawaiian Poi Dog', 'DOG', '381', 'dev'),
  ('Heeler', 'DOG', '982', 'dev'),
  ('Highland lynx ', 'DOG', '936', 'dev'),
  ('Hokkaido Ken', 'DOG', '383', 'dev'),
  ('Hortaya Borzaya', 'DOG', '384', 'dev'),
  ('Hound', 'DOG', '937', 'dev'),
  ('Hound ', 'DOG', '978', 'dev'),
  ('Hound  Mix', 'DOG', '811', 'dev'),
  ('Hound Mix', 'DOG', '992', 'dev'),
  ('Hovawart', 'DOG', '385', 'dev'),
  ('Hungarian Breed', 'DOG', '979', 'dev'),
  ('Hungarian Scottish Terrier', 'DOG', '980', 'dev'),
  ('Huntaway', 'DOG', '386', 'dev'),
  ('Husky', 'DOG', '684', 'dev'),
  ('Husky Mix', 'DOG', '681', 'dev'),
  ('Hygenhund', 'DOG', '387', 'dev'),
  ('Ibizan Hound', 'DOG', '388', 'dev'),
  ('Ibizan Hound Mix', 'DOG', '904', 'dev'),
  ('Icelandic Sheepdog', 'DOG', '389', 'dev'),
  ('Imperial Shih Tzu', 'DOG', '751', 'dev'),
  ('Indian pariah dog', 'DOG', '390', 'dev'),
  ('Indian Spitz', 'DOG', '391', 'dev'),
  ('Irish Red and White Setter', 'DOG', '392', 'dev'),
  ('Irish Setter', 'DOG', '393', 'dev'),
  ('Irish Setter Mix', 'DOG', '850', 'dev'),
  ('Irish Terrier', 'DOG', '394', 'dev'),
  ('Irish Terrier Mix', 'DOG', '916', 'dev'),
  ('Irish Water Spaniel', 'DOG', '395', 'dev'),
  ('Irish Wolfhound', 'DOG', '396', 'dev'),
  ('Irish Wolfhound Mix', 'DOG', '905', 'dev'),
  ('Istrian Coarse-haired Hound', 'DOG', '397', 'dev'),
  ('Istrian Shorthaired Hound', 'DOG', '398', 'dev'),
  ('Italian Greyhound', 'DOG', '399', 'dev'),
  ('Italian Greyhound Mix', 'DOG', '898', 'dev'),
  ('Italian Water Dog', 'DOG', '859', 'dev'),
  ('Jack Russell Terrier', 'DOG', '15', 'dev'),
  ('Jack Russell Terrier Mix', 'DOG', '665', 'dev'),
  ('Jagdterrier', 'DOG', '401', 'dev'),
  ('Japanese Chin', 'DOG', '403', 'dev'),
  ('Japanese Chin Mix', 'DOG', '930', 'dev'),
  ('Japanese Spitz', 'DOG', '404', 'dev'),
  ('Japanese Terrier', 'DOG', '405', 'dev'),
  ('Jämthund', 'DOG', '402', 'dev'),
  ('Kai Ken', 'DOG', '407', 'dev'),
  ('Kaikadi', 'DOG', '406', 'dev'),
  ('Kangal Dog', 'DOG', '408', 'dev'),
  ('Kanni', 'DOG', '409', 'dev'),
  ('Karakachan Dog', 'DOG', '410', 'dev'),
  ('Karelian Bear Dog', 'DOG', '411', 'dev'),
  ('Karst Shepherd', 'DOG', '412', 'dev'),
  ('Keeshond', 'DOG', '413', 'dev'),
  ('Keeshond Mix', 'DOG', '941', 'dev'),
  ('Kerry Beagle', 'DOG', '414', 'dev'),
  ('Kerry Blue Terrier', 'DOG', '415', 'dev'),
  ('King Charles Spaniel', 'DOG', '416', 'dev'),
  ('King Shepherd', 'DOG', '417', 'dev'),
  ('Kintamani', 'DOG', '418', 'dev'),
  ('Kishu Ken', 'DOG', '419', 'dev'),
  ('Komondor', 'DOG', '420', 'dev'),
  ('Kooikerhondje', 'DOG', '421', 'dev'),
  ('Koolie', 'DOG', '422', 'dev'),
  ('Korean Jindo Dog', 'DOG', '423', 'dev'),
  ('Kromfohrländer', 'DOG', '424', 'dev'),
  ('Kumaon Mastiff', 'DOG', '425', 'dev'),
  ('Kunming Wolfdog', 'DOG', '426', 'dev'),
  ('Kuvasz', 'DOG', '427', 'dev'),
  ('Kyi-Leo', 'DOG', '428', 'dev'),
  ('Lab Mix', 'DOG', '651', 'dev'),
  ('Lab/Mastiff Mix', 'DOG', '657', 'dev'),
  ('Labradoodle', 'DOG', '25', 'dev'),
  ('Labrador / German Shepard Cross', 'DOG', '653', 'dev'),
  ('Labrador Husky', 'DOG', '429', 'dev'),
  ('Labrador Mix', 'DOG', '663', 'dev'),
  ('Labrador Retriever', 'DOG', '27', 'dev'),
  ('Lagotto Romagnolo', 'DOG', '430', 'dev'),
  ('Lakeland Terrier', 'DOG', '431', 'dev'),
  ('Lancashire Heeler', 'DOG', '432', 'dev'),
  ('Landseer', 'DOG', '433', 'dev'),
  ('Lapponian Herder', 'DOG', '434', 'dev'),
  ('Leonberger', 'DOG', '435', 'dev'),
  ('Leonberger Mix', 'DOG', '970', 'dev'),
  ('Lhasa Apso', 'DOG', '436', 'dev'),
  ('Lhasa Apso Mix', 'DOG', '729', 'dev'),
  ('Lithuanian Hound', 'DOG', '437', 'dev'),
  ('llewellin setter', 'DOG', '974', 'dev')
ON CONFLICT (name, species, "tenantId") DO NOTHING;

INSERT INTO breeds (name, species, "gingrId", "tenantId") VALUES
  ('Long Hair Calico', 'DOG', '921', 'dev'),
  ('Longhaired', 'DOG', '925', 'dev'),
  ('Longhaired Calico', 'DOG', '886', 'dev'),
  ('Longhaired Whippet', 'DOG', '438', 'dev'),
  ('Löwchen', 'DOG', '439', 'dev'),
  ('Magyar Agár', 'DOG', '440', 'dev'),
  ('Mahratta Greyhound', 'DOG', '441', 'dev'),
  ('Majorca Shepherd Dog', 'DOG', '442', 'dev'),
  ('Malamute', 'DOG', '851', 'dev'),
  ('Malamute Mix', 'DOG', '870', 'dev'),
  ('Maltese', 'DOG', '443', 'dev'),
  ('Maltese Mix', 'DOG', '781', 'dev'),
  ('Maltipoo', 'DOG', '86', 'dev'),
  ('Maltise', 'DOG', '983', 'dev'),
  ('Manchester Terrier', 'DOG', '444', 'dev'),
  ('Maremma Sheepdog', 'DOG', '445', 'dev'),
  ('Mastiff', 'DOG', '814', 'dev'),
  ('Mastiff Mix', 'DOG', '764', 'dev'),
  ('McNab', 'DOG', '446', 'dev'),
  ('Med Mix', 'DOG', '972', 'dev'),
  ('Med Mix Breed', 'DOG', '852', 'dev'),
  ('Med Mixed', 'DOG', '837', 'dev'),
  ('medium hair tabby', 'DOG', '945', 'dev'),
  ('Mexican Hairless Dog', 'DOG', '447', 'dev'),
  ('Mini Aussiedoodle', 'DOG', '807', 'dev'),
  ('Mini Bull Terrier', 'DOG', '962', 'dev'),
  ('Mini Doodle', 'DOG', '765', 'dev'),
  ('mini goldendoodle', 'DOG', '990', 'dev'),
  ('Mini Labradoodle', 'DOG', '914', 'dev'),
  ('Mini-Aussiedoodle', 'DOG', '984', 'dev'),
  ('Miniature American Shepherd', 'DOG', '449', 'dev'),
  ('Miniature Australian Shepherd', 'DOG', '448', 'dev'),
  ('Miniature Dachshund', 'DOG', '143', 'dev'),
  ('Miniature Fox Terrier', 'DOG', '450', 'dev'),
  ('Miniature Pinscher', 'DOG', '451', 'dev'),
  ('miniature pinscher mix', 'DOG', '798', 'dev'),
  ('Miniature Poodle', 'DOG', '724', 'dev'),
  ('Miniature Poodle Mix', 'DOG', '797', 'dev'),
  ('Miniature Schnauzer', 'DOG', '17', 'dev'),
  ('Miniature schnauzer mix', 'DOG', '831', 'dev'),
  ('Miniature Shar Pei', 'DOG', '453', 'dev'),
  ('Miniature Welsh Terrier', 'DOG', '981', 'dev'),
  ('Mioritic', 'DOG', '454', 'dev'),
  ('Mixed', 'DOG', '58', 'dev'),
  ('miz', 'DOG', '988', 'dev'),
  ('Molossus', 'DOG', '455', 'dev'),
  ('Montenegrin Mountain Hound', 'DOG', '456', 'dev'),
  ('Morkie', 'DOG', '712', 'dev'),
  ('Moscow Watchdog', 'DOG', '457', 'dev'),
  ('Moscow Water Dog', 'DOG', '458', 'dev'),
  ('Mountain Cur', 'DOG', '459', 'dev'),
  ('Moyen Poodle', 'DOG', '780', 'dev'),
  ('Mucuchies', 'DOG', '460', 'dev'),
  ('Mudhol Hound', 'DOG', '461', 'dev'),
  ('Mudi', 'DOG', '462', 'dev'),
  ('Multi-poo', 'DOG', '660', 'dev'),
  ('Münsterländer, Large', 'DOG', '463', 'dev'),
  ('Münsterländer, Small', 'DOG', '464', 'dev'),
  ('Native Indian', 'DOG', '933', 'dev'),
  ('Neapolitan Mastiff', 'DOG', '465', 'dev'),
  ('New Zealand Heading Dog', 'DOG', '467', 'dev'),
  ('Newfoundland', 'DOG', '466', 'dev'),
  ('Newfoundland Mix', 'DOG', '855', 'dev'),
  ('Norfolk Spaniel', 'DOG', '468', 'dev'),
  ('Norfolk Terrier', 'DOG', '469', 'dev'),
  ('Norrbottenspets', 'DOG', '470', 'dev'),
  ('North Country Beagle', 'DOG', '471', 'dev'),
  ('Northern Inuit Dog', 'DOG', '472', 'dev'),
  ('Norwegian Buhund', 'DOG', '473', 'dev'),
  ('Norwegian Elkhound', 'DOG', '474', 'dev'),
  ('Norwegian Lundehund', 'DOG', '475', 'dev'),
  ('Norwich Terrier', 'DOG', '476', 'dev'),
  ('Nova Scotia Duck-Tolling Retriever', 'DOG', '477', 'dev'),
  ('Old Croatian Sighthound', 'DOG', '478', 'dev'),
  ('Old Danish Pointer', 'DOG', '479', 'dev'),
  ('Old English Bulldog', 'DOG', '720', 'dev'),
  ('Old English Sheepdog', 'DOG', '480', 'dev'),
  ('Old English Terrier', 'DOG', '481', 'dev'),
  ('Old German Shepherd Dog', 'DOG', '482', 'dev'),
  ('Old Time Farm Shepherd', 'DOG', '483', 'dev'),
  ('Orange Tabby', 'DOG', '650', 'dev'),
  ('Otterhound', 'DOG', '485', 'dev'),
  ('Pachon Navarro', 'DOG', '486', 'dev'),
  ('Paisley Terrier', 'DOG', '488', 'dev'),
  ('Pandikona', 'DOG', '487', 'dev'),
  ('Papillon', 'DOG', '489', 'dev'),
  ('Papillon MIX', 'DOG', '909', 'dev'),
  ('Parson Russell Terrier', 'DOG', '490', 'dev'),
  ('Parson Terrier Mix', 'DOG', '971', 'dev'),
  ('Patterdale Terrier', 'DOG', '491', 'dev'),
  ('Patterdale Terrior X', 'DOG', '843', 'dev'),
  ('Peekapoo', 'DOG', '849', 'dev'),
  ('Pekingese', 'DOG', '492', 'dev'),
  ('Pekingese  Mix', 'DOG', '880', 'dev'),
  ('Pembroke Welsh Corgi', 'DOG', '674', 'dev'),
  ('Perro de Presa Canario', 'DOG', '493', 'dev'),
  ('Perro de Presa Mallorquin', 'DOG', '494', 'dev'),
  ('Perro fino Colombiano', 'DOG', '495', 'dev'),
  ('Peruvian Hairless Dog', 'DOG', '496', 'dev'),
  ('Phalène', 'DOG', '497', 'dev')
ON CONFLICT (name, species, "tenantId") DO NOTHING;

INSERT INTO breeds (name, species, "gingrId", "tenantId") VALUES
  ('Pharaoh Hound', 'DOG', '498', 'dev'),
  ('Pharaoh Hound Mix', 'DOG', '968', 'dev'),
  ('Phu Quoc ridgeback dog', 'DOG', '499', 'dev'),
  ('Picardy Spaniel', 'DOG', '500', 'dev'),
  ('Pit Bull', 'DOG', '666', 'dev'),
  ('Pit Bull mix', 'DOG', '56', 'dev'),
  ('Plott Hound', 'DOG', '501', 'dev'),
  ('Plott Hound Mix', 'DOG', '825', 'dev'),
  ('Podenco Canario', 'DOG', '502', 'dev'),
  ('Pointer', 'DOG', '503', 'dev'),
  ('Pointer Mix', 'DOG', '109', 'dev'),
  ('Poitevin', 'DOG', '504', 'dev'),
  ('Polish Greyhound', 'DOG', '505', 'dev'),
  ('Polish Hound', 'DOG', '506', 'dev'),
  ('Polish Hunting Dog', 'DOG', '507', 'dev'),
  ('Polish Lowland Sheepdog', 'DOG', '508', 'dev'),
  ('Polish Tatra Sheepdog', 'DOG', '509', 'dev'),
  ('Pomapoo', 'DOG', '951', 'dev'),
  ('Pomeranian', 'DOG', '18', 'dev'),
  ('Pomeranian Mix', 'DOG', '698', 'dev'),
  ('Pomsky', 'DOG', '750', 'dev'),
  ('Pont-Audemer Spaniel', 'DOG', '511', 'dev'),
  ('Poodle', 'DOG', '19', 'dev'),
  ('Poodle Mix', 'DOG', '730', 'dev'),
  ('Porcelaine', 'DOG', '513', 'dev'),
  ('Portuguese Podengo', 'DOG', '514', 'dev'),
  ('Portuguese Pointer', 'DOG', '515', 'dev'),
  ('Portuguese Water Dog', 'DOG', '516', 'dev'),
  ('Posavac Hound', 'DOG', '517', 'dev'),
  ('Pudelpointer', 'DOG', '518', 'dev'),
  ('Pug', 'DOG', '519', 'dev'),
  ('Pug Mix', 'DOG', '793', 'dev'),
  ('Puggle', 'DOG', '875', 'dev'),
  ('Puggle Mix', 'DOG', '802', 'dev'),
  ('Puli', 'DOG', '520', 'dev'),
  ('Pumi', 'DOG', '521', 'dev'),
  ('Pungsan Dog', 'DOG', '522', 'dev'),
  ('Pyrenean Mastiff', 'DOG', '523', 'dev'),
  ('Pyrenean Shepherd', 'DOG', '524', 'dev'),
  ('Rafeiro do Alentejo', 'DOG', '525', 'dev'),
  ('Rajapalayam', 'DOG', '526', 'dev'),
  ('Rampur Greyhound', 'DOG', '527', 'dev'),
  ('Rastreador Brasileiro', 'DOG', '528', 'dev'),
  ('Rat Terrier', 'DOG', '531', 'dev'),
  ('Rat Terrier Mix', 'DOG', '671', 'dev'),
  ('Ratonero Bodeguero Andaluz', 'DOG', '529', 'dev'),
  ('Ratonero Valenciano', 'DOG', '530', 'dev'),
  ('Redbone Coonhound', 'DOG', '532', 'dev'),
  ('Redbone Coonhound Mix', 'DOG', '841', 'dev'),
  ('Redtick Coonhound', 'DOG', '947', 'dev'),
  ('Redtick coonhound mix', 'DOG', '838', 'dev'),
  ('Retriever Mix', 'DOG', '652', 'dev'),
  ('Rhodesian Ridgeback', 'DOG', '533', 'dev'),
  ('Rhodesian Ridgeback Mix', 'DOG', '714', 'dev'),
  ('Rottweiler', 'DOG', '534', 'dev'),
  ('Rottweiler Mix', 'DOG', '691', 'dev'),
  ('Russell Terrier', 'DOG', '539', 'dev'),
  ('Russell Terrier Mix', 'DOG', '918', 'dev'),
  ('Russian Spaniel', 'DOG', '535', 'dev'),
  ('Russian Toy', 'DOG', '536', 'dev'),
  ('Russian Tracker', 'DOG', '537', 'dev'),
  ('Russo-European Laika', 'DOG', '538', 'dev'),
  ('Saarlooswolfhond', 'DOG', '540', 'dev'),
  ('Sabueso Español', 'DOG', '541', 'dev'),
  ('Saint Bernard', 'DOG', '659', 'dev'),
  ('Saint bernard mix', 'DOG', '794', 'dev'),
  ('Saint-Usuge Spaniel', 'DOG', '542', 'dev'),
  ('Sakhalin Husky', 'DOG', '543', 'dev'),
  ('Saluki', 'DOG', '544', 'dev'),
  ('Saluki Mix', 'DOG', '919', 'dev'),
  ('Samoyed', 'DOG', '545', 'dev'),
  ('Samoyed Mix', 'DOG', '954', 'dev'),
  ('Santal Hound', 'DOG', '546', 'dev'),
  ('Sapsali', 'DOG', '547', 'dev'),
  ('Sarplananiac', 'DOG', '876', 'dev'),
  ('Schapendoes', 'DOG', '548', 'dev'),
  ('Schillerstövare', 'DOG', '549', 'dev'),
  ('Schipperke', 'DOG', '550', 'dev'),
  ('Schnauzer', 'DOG', '688', 'dev'),
  ('Schnauzer Mix', 'DOG', '759', 'dev'),
  ('Schnauzer/Poodle', 'DOG', '80', 'dev'),
  ('Schnoodle', 'DOG', '726', 'dev'),
  ('Schweizer Laufhund', 'DOG', '552', 'dev'),
  ('Schweizerischer Niederlaufhund', 'DOG', '553', 'dev'),
  ('Scotch Collie', 'DOG', '554', 'dev'),
  ('Scottish Deerhound', 'DOG', '555', 'dev'),
  ('Scottish Terrier', 'DOG', '556', 'dev'),
  ('Scottish Terrier Mix', 'DOG', '715', 'dev'),
  ('Sealyham Terrier', 'DOG', '557', 'dev'),
  ('Segugio Italiano', 'DOG', '558', 'dev'),
  ('Seppala Siberian Sleddog', 'DOG', '559', 'dev'),
  ('Serbian Hound', 'DOG', '560', 'dev'),
  ('Serbian Tricolour Hound', 'DOG', '561', 'dev'),
  ('Seskar Seal Dog', 'DOG', '562', 'dev'),
  ('Shar Pei', 'DOG', '563', 'dev'),
  ('Shar Pei Mix', 'DOG', '833', 'dev'),
  ('Sheep Dog Mix', 'DOG', '888', 'dev'),
  ('Sheepadoodle', 'DOG', '741', 'dev'),
  ('Sheltie', 'DOG', '732', 'dev'),
  ('Shepherd Mix', 'DOG', '133', 'dev')
ON CONFLICT (name, species, "tenantId") DO NOTHING;

INSERT INTO breeds (name, species, "gingrId", "tenantId") VALUES
  ('Shetland Sheepdog', 'DOG', '20', 'dev'),
  ('Shetland Sheepdog', 'DOG', '20', 'dev'),
  ('Shetland Sheepdog Mix', 'DOG', '783', 'dev'),
  ('Shiba Inu', 'DOG', '565', 'dev'),
  ('Shiba Inu Mix', 'DOG', '857', 'dev'),
  ('Shih Tzu', 'DOG', '21', 'dev'),
  ('Shih Tzu Mix', 'DOG', '701', 'dev'),
  ('Shihpoo', 'DOG', '993', 'dev'),
  ('Shikoku Ken', 'DOG', '567', 'dev'),
  ('Shiloh Shepherd Dog', 'DOG', '568', 'dev'),
  ('Siberian Husky', 'DOG', '22', 'dev'),
  ('Siberian Husky Mix', 'DOG', '762', 'dev'),
  ('Silken Windhound', 'DOG', '570', 'dev'),
  ('Silky Terrier', 'DOG', '957', 'dev'),
  ('Sinhala Hound', 'DOG', '571', 'dev'),
  ('Skye Terrier', 'DOG', '572', 'dev'),
  ('Sloughi', 'DOG', '573', 'dev'),
  ('Slovak Cuvac', 'DOG', '574', 'dev'),
  ('Slovakian Rough-Haired Pointer', 'DOG', '575', 'dev'),
  ('Slovenský Kopov', 'DOG', '576', 'dev'),
  ('Small Greek Domestic Dog', 'DOG', '578', 'dev'),
  ('Smålandsstövare', 'DOG', '577', 'dev'),
  ('Soft-Coated Wheaten Terrier', 'DOG', '23', 'dev'),
  ('South Russian Ovcharka', 'DOG', '580', 'dev'),
  ('Southern Hound', 'DOG', '581', 'dev'),
  ('Spaniel Mix', 'DOG', '926', 'dev'),
  ('Spanish Grey Hound', 'DOG', '845', 'dev'),
  ('Spanish Mastiff', 'DOG', '582', 'dev'),
  ('Spanish Water Dog', 'DOG', '583', 'dev'),
  ('Spinone Italiano', 'DOG', '584', 'dev'),
  ('Spitz', 'DOG', '932', 'dev'),
  ('Sporting Lucas Terrier', 'DOG', '585', 'dev'),
  ('Springer Spaniel', 'DOG', '844', 'dev'),
  ('Springer Spaniel Mix', 'DOG', '901', 'dev'),
  ('St. Bernard', 'DOG', '586', 'dev'),
  ('St. Bernard Mix', 'DOG', '737', 'dev'),
  ('St. John''s water dog', 'DOG', '587', 'dev'),
  ('Stabyhoun', 'DOG', '588', 'dev'),
  ('Staffordshire Bull Terrier', 'DOG', '589', 'dev'),
  ('Staffordshire Mix', 'DOG', '699', 'dev'),
  ('Standard Poodle', 'DOG', '661', 'dev'),
  ('Standard Poodle Mix', 'DOG', '869', 'dev'),
  ('Standard Schnauzer', 'DOG', '551', 'dev'),
  ('Stephens Cur', 'DOG', '590', 'dev'),
  ('Styrian Coarse-haired Hound', 'DOG', '591', 'dev'),
  ('Sussex Spaniel', 'DOG', '592', 'dev'),
  ('Swedish Lapphund', 'DOG', '593', 'dev'),
  ('Swedish Vallhund', 'DOG', '594', 'dev'),
  ('Tahltan Bear Dog', 'DOG', '595', 'dev'),
  ('Taigan', 'DOG', '596', 'dev'),
  ('Talbot', 'DOG', '597', 'dev'),
  ('Tamaskan Dog', 'DOG', '598', 'dev'),
  ('Teddy Roosevelt Terrier', 'DOG', '599', 'dev'),
  ('Telomian', 'DOG', '600', 'dev'),
  ('Tennessee Treeing Brindle', 'DOG', '601', 'dev'),
  ('Tenterfield Terrier', 'DOG', '602', 'dev'),
  ('Terceira Mastiff', 'DOG', '603', 'dev'),
  ('Terrier Mix', 'DOG', '704', 'dev'),
  ('Texas Heeler', 'DOG', '864', 'dev'),
  ('Thai Bangkaew Dog', 'DOG', '604', 'dev'),
  ('Thai Ridgeback', 'DOG', '605', 'dev'),
  ('Tibetan Mastiff', 'DOG', '606', 'dev'),
  ('Tibetan Mix', 'DOG', '931', 'dev'),
  ('Tibetan Spaniel', 'DOG', '607', 'dev'),
  ('Tibetan Terrier', 'DOG', '608', 'dev'),
  ('Tornjak', 'DOG', '609', 'dev'),
  ('Tosa', 'DOG', '610', 'dev'),
  ('Tosa/Rod Ridgebck', 'DOG', '848', 'dev'),
  ('Toy Bulldog', 'DOG', '611', 'dev'),
  ('Toy Fox Terrier', 'DOG', '612', 'dev'),
  ('Toy Manchester Terrier', 'DOG', '613', 'dev'),
  ('Toy Poodle', 'DOG', '709', 'dev'),
  ('Toy Poodle Mix', 'DOG', '892', 'dev'),
  ('Toy Trawler Spaniel', 'DOG', '614', 'dev'),
  ('Transylvanian Hound', 'DOG', '615', 'dev'),
  ('Treeing Cur', 'DOG', '616', 'dev'),
  ('Treeing Walker Coonhound', 'DOG', '617', 'dev'),
  ('Treeing walker coonhound mix', 'DOG', '910', 'dev'),
  ('Trigg Hound', 'DOG', '618', 'dev'),
  ('Tweed Water Spaniel', 'DOG', '619', 'dev'),
  ('Tyrolean Hound', 'DOG', '620', 'dev'),
  ('Uruguayan Cimarron', 'DOG', '621', 'dev'),
  ('Vanjari Hound', 'DOG', '622', 'dev'),
  ('Victorian Bulldog', 'DOG', '924', 'dev'),
  ('Villano de las Encartaciones', 'DOG', '623', 'dev'),
  ('Vizsla', 'DOG', '644', 'dev'),
  ('Vizsla Mix', 'DOG', '946', 'dev'),
  ('Volpino Italiano', 'DOG', '625', 'dev'),
  ('Weimaraner', 'DOG', '626', 'dev'),
  ('Weimaraner Mix', 'DOG', '885', 'dev'),
  ('Welsh Corgi', 'DOG', '779', 'dev'),
  ('Welsh Corgi Mix', 'DOG', '815', 'dev'),
  ('Welsh Corgi, Cardigan', 'DOG', '627', 'dev'),
  ('Welsh Corgi, Pembroke', 'DOG', '628', 'dev'),
  ('Welsh Sheepdog', 'DOG', '629', 'dev'),
  ('Welsh Springer Spaniel', 'DOG', '630', 'dev'),
  ('Welsh Terrier', 'DOG', '631', 'dev'),
  ('West Highland Terrier', 'DOG', '116', 'dev'),
  ('West Highland White Terrier', 'DOG', '632', 'dev'),
  ('West Siberian Laika', 'DOG', '633', 'dev')
ON CONFLICT (name, species, "tenantId") DO NOTHING;

INSERT INTO breeds (name, species, "gingrId", "tenantId") VALUES
  ('Westie Mix', 'DOG', '700', 'dev'),
  ('Westphalian Dachsbracke', 'DOG', '634', 'dev'),
  ('Wetterhound', 'DOG', '635', 'dev'),
  ('Wheaten Mix', 'DOG', '927', 'dev'),
  ('Wheaten Terrier', 'DOG', '913', 'dev'),
  ('Whippet', 'DOG', '636', 'dev'),
  ('Whippet Mix', 'DOG', '734', 'dev'),
  ('White Shepherd', 'DOG', '637', 'dev'),
  ('Wire Fox Terrier', 'DOG', '647', 'dev'),
  ('Wire Hair Fox Terrier', 'DOG', '719', 'dev'),
  ('Wirehair Terrier Mix', 'DOG', '773', 'dev'),
  ('Wirehaired Pointing Griffon', 'DOG', '638', 'dev'),
  ('Wirehaired Vizsla', 'DOG', '639', 'dev'),
  ('Wolf Hybrid', 'DOG', '884', 'dev'),
  ('Yorkie', 'DOG', '686', 'dev'),
  ('Yorkie Mix', 'DOG', '673', 'dev'),
  ('Yorkie poo ', 'DOG', '731', 'dev'),
  ('Yorkshire Terrier', 'DOG', '24', 'dev')
ON CONFLICT (name, species, "tenantId") DO NOTHING;


-- CAT breeds (136)
INSERT INTO breeds (name, species, "gingrId", "tenantId") VALUES
  ('Abbysinian/Siamese', 'CAT', '854', 'dev'),
  ('Abyssinian', 'CAT', '668', 'dev'),
  ('Alley Cat', 'CAT', '806', 'dev'),
  ('American Cattle Dog', 'CAT', '985', 'dev'),
  ('American Shorthair', 'CAT', '679', 'dev'),
  ('Australian Cattle Dog', 'CAT', '333', 'dev'),
  ('Australian Cattle dog Mix', 'CAT', '667', 'dev'),
  ('Bengal cat', 'CAT', '952', 'dev'),
  ('Black Cat', 'CAT', '746', 'dev'),
  ('black persian', 'CAT', '966', 'dev'),
  ('Black Shorthair Cat', 'CAT', '834', 'dev'),
  ('Bombay', 'CAT', '891', 'dev'),
  ('Burmese Cat', 'CAT', '821', 'dev'),
  ('cat dsh', 'CAT', '796', 'dev'),
  ('Cat: American Shorthair', 'CAT', '173', 'dev'),
  ('Cat: American Wirehair', 'CAT', '179', 'dev'),
  ('Cat: Arabian Mau', 'CAT', '29', 'dev'),
  ('Cat: Asian', 'CAT', '138', 'dev'),
  ('Cat: Asian Semi-longhair', 'CAT', '137', 'dev'),
  ('Cat: Australian Mist', 'CAT', '180', 'dev'),
  ('Cat: Balinese', 'CAT', '197', 'dev'),
  ('Cat: Bambino', 'CAT', '198', 'dev'),
  ('Cat: Bengal', 'CAT', '181', 'dev'),
  ('Cat: Birman', 'CAT', '199', 'dev'),
  ('Cat: Bombay', 'CAT', '182', 'dev'),
  ('Cat: Brazilian Shorthair', 'CAT', '200', 'dev'),
  ('Cat: British Longhair', 'CAT', '202', 'dev'),
  ('Cat: British Semi-longhair', 'CAT', '183', 'dev'),
  ('Cat: British Shorthair', 'CAT', '201', 'dev'),
  ('Cat: Burmese', 'CAT', '203', 'dev'),
  ('Cat: Burmilla', 'CAT', '204', 'dev'),
  ('Cat: California Spangled', 'CAT', '205', 'dev'),
  ('Cat: Chantilly-Tiffany', 'CAT', '206', 'dev'),
  ('Cat: Chartreux', 'CAT', '207', 'dev'),
  ('Cat: Chausie', 'CAT', '208', 'dev'),
  ('Cat: Cheetoh', 'CAT', '209', 'dev'),
  ('Cat: Colorpoint Shorthair', 'CAT', '210', 'dev'),
  ('Cat: Cornish Rex', 'CAT', '211', 'dev'),
  ('Cat: Cymric,  or Manx Longhair', 'CAT', '212', 'dev'),
  ('Cat: Cyprus', 'CAT', '213', 'dev'),
  ('Cat: Devon Rex', 'CAT', '214', 'dev'),
  ('Cat: Domestic Longhair (DLH)', 'CAT', '675', 'dev'),
  ('Cat: Domestic Shorthair (DSH)', 'CAT', '669', 'dev'),
  ('Cat: Donskoy,  or Don Sphynx', 'CAT', '215', 'dev'),
  ('Cat: Dragon Li', 'CAT', '216', 'dev'),
  ('Cat: Dwarf cat,  or Dwelf', 'CAT', '184', 'dev'),
  ('Cat: Egyptian Mau', 'CAT', '185', 'dev'),
  ('Cat: European Shorthair', 'CAT', '217', 'dev'),
  ('Cat: Exotic ShortHair', 'CAT', '186', 'dev'),
  ('Cat: FoldEx Cat (Official Breed - CCA/AFC)[1]', 'CAT', '187', 'dev'),
  ('Cat: German Rex', 'CAT', '188', 'dev'),
  ('Cat: Havana Brown', 'CAT', '218', 'dev'),
  ('Cat: Highlander', 'CAT', '219', 'dev'),
  ('Cat: Himalayan,  or Colorpoint Persian', 'CAT', '220', 'dev'),
  ('Cat: Japanese Bobtail', 'CAT', '221', 'dev'),
  ('Cat: Javanese', 'CAT', '222', 'dev'),
  ('Cat: Khao Manee', 'CAT', '190', 'dev'),
  ('Cat: Korat', 'CAT', '191', 'dev'),
  ('Cat: Korean Bobtail', 'CAT', '223', 'dev'),
  ('Cat: Korn Ja', 'CAT', '192', 'dev'),
  ('Cat: Kurilian Bobtail', 'CAT', '189', 'dev'),
  ('Cat: LaPerm', 'CAT', '225', 'dev'),
  ('Cat: Lykoi', 'CAT', '226', 'dev'),
  ('Cat: Maine Coon', 'CAT', '193', 'dev'),
  ('Cat: Manx', 'CAT', '227', 'dev'),
  ('Cat: Mekong Bobtail', 'CAT', '228', 'dev'),
  ('Cat: Minskin', 'CAT', '229', 'dev'),
  ('Cat: Munchkin', 'CAT', '230', 'dev'),
  ('Cat: Napoleon', 'CAT', '232', 'dev'),
  ('Cat: Nebelung', 'CAT', '231', 'dev'),
  ('Cat: Norwegian Forest Cat', 'CAT', '233', 'dev'),
  ('Cat: Ocicat', 'CAT', '234', 'dev'),
  ('Cat: Ojos Azules', 'CAT', '235', 'dev'),
  ('Cat: Oregon Rex', 'CAT', '236', 'dev'),
  ('Cat: Oriental Bicolor', 'CAT', '237', 'dev'),
  ('Cat: Oriental Longhair', 'CAT', '239', 'dev'),
  ('Cat: Oriental Shorthair', 'CAT', '238', 'dev'),
  ('Cat: PerFold Cat (Experimental Breed - WCF)', 'CAT', '240', 'dev'),
  ('Cat: Persian (Modern Persian Cat)', 'CAT', '241', 'dev'),
  ('Cat: Peterbald', 'CAT', '194', 'dev'),
  ('Cat: Pixie-bob', 'CAT', '195', 'dev'),
  ('Cat: Raas', 'CAT', '242', 'dev'),
  ('Cat: Ragamuffin', 'CAT', '243', 'dev'),
  ('Cat: Ragdoll', 'CAT', '244', 'dev'),
  ('Cat: Russian Blue', 'CAT', '245', 'dev'),
  ('Cat: Russian White, Black and Tabby', 'CAT', '196', 'dev'),
  ('Cat: Sabre Tooth', 'CAT', '641', 'dev'),
  ('Cat: Sam Sawet', 'CAT', '246', 'dev'),
  ('Cat: Savannah', 'CAT', '30', 'dev'),
  ('Cat: Scottish Fold', 'CAT', '33', 'dev'),
  ('Cat: Selkirk Rex', 'CAT', '97', 'dev'),
  ('Cat: Serengeti', 'CAT', '172', 'dev'),
  ('Cat: Serrade petit', 'CAT', '171', 'dev'),
  ('Cat: Siamese', 'CAT', '170', 'dev'),
  ('Cat: Siberian', 'CAT', '169', 'dev'),
  ('Cat: Singapura', 'CAT', '168', 'dev'),
  ('Cat: Snowshoe', 'CAT', '167', 'dev'),
  ('Cat: Sokoke', 'CAT', '16', 'dev'),
  ('Cat: Somali', 'CAT', '61', 'dev'),
  ('Cat: Sphynx', 'CAT', '60', 'dev')
ON CONFLICT (name, species, "tenantId") DO NOTHING;

INSERT INTO breeds (name, species, "gingrId", "tenantId") VALUES
  ('Cat: Tabby', 'CAT', '687', 'dev'),
  ('Cat: Thai', 'CAT', '59', 'dev'),
  ('Cat: Tonkinese', 'CAT', '99', 'dev'),
  ('Cat: Toyger', 'CAT', '127', 'dev'),
  ('Cat: Traditional Persian,  or Doll Face Persian', 'CAT', '165', 'dev'),
  ('Cat: Turkish Angora', 'CAT', '36', 'dev'),
  ('Cat: Turkish Van', 'CAT', '12', 'dev'),
  ('Cat: Ukrainian Levkoy', 'CAT', '39', 'dev'),
  ('Cat: York Chocolate', 'CAT', '94', 'dev'),
  ('catahoula', 'CAT', '861', 'dev'),
  ('Catahoula Cur', 'CAT', '166', 'dev'),
  ('Catahoula Mix', 'CAT', '161', 'dev'),
  ('Catalan Sheepdog', 'CAT', '164', 'dev'),
  ('Exotic Long haired lilac Persian', 'CAT', '778', 'dev'),
  ('Galician Cattle Dog', 'CAT', '67', 'dev'),
  ('Gray cat', 'CAT', '942', 'dev'),
  ('Grey Cat', 'CAT', '911', 'dev'),
  ('Grey Tiger Cat', 'CAT', '842', 'dev'),
  ('Himalayan Mix', 'CAT', '923', 'dev'),
  ('Himalayan Sheepdog', 'CAT', '382', 'dev'),
  ('Long hair cat', 'CAT', '742', 'dev'),
  ('Long Hair Maine Coon', 'CAT', '805', 'dev'),
  ('Longhair Persian', 'CAT', '874', 'dev'),
  ('Maine Coon', 'CAT', '754', 'dev'),
  ('Maine Coon Mix', 'CAT', '745', 'dev'),
  ('Manx Cat', 'CAT', '955', 'dev'),
  ('Norwegian Forest Cat', 'CAT', '893', 'dev'),
  ('Persian', 'CAT', '964', 'dev'),
  ('Ragdoll', 'CAT', '953', 'dev'),
  ('Ragdoll Mix', 'CAT', '902', 'dev'),
  ('Russian Blue', 'CAT', '705', 'dev'),
  ('Scottish Fold', 'CAT', '956', 'dev'),
  ('Siamese', 'CAT', '858', 'dev'),
  ('Siamese Mix', 'CAT', '755', 'dev'),
  ('Sphynx', 'CAT', '840', 'dev'),
  ('Turkish Van', 'CAT', '949', 'dev')
ON CONFLICT (name, species, "tenantId") DO NOTHING;

-- Total breeds inserted: 954
